name: CI Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - 'apps/core-service/**'
      - '.github/workflows/ci-backend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/core-service

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and Test with Maven
      run: mvn -B package --file pom.xml
